### ISSUE TITLE
Can not load the data of VOC.

### ISSUE THREAD

**Issue by JimZAI** [deeplearning-wisc/siren#2]
Hi, thanks for your insightful work.

When i tried to reproduce the results of "SIREN on VOC", a bug occurred:

Traceback (most recent call last):
  File "/home/xxx/OOD-project/siren-main/detr/main.py", line 360, in <module>
    main(args)
  File "/home/xxx/OOD-project/siren-main/detr/main.py", line 72, in main
    dataset_train, dataset_val = get_datasets(args)
  File "/home/xxx/OOD-project/siren-main/detr/main.py", line 307, in get_datasets
    dataset_train = VOCDetection(args.voc_path, ["2007", "2012"], image_sets=['trainval', 'trainval'],
  File "/home/xxx/OOD-project/siren-main/detr/datasets/torchvision_datasets/voc.py", line 121, in __init__
    raise RuntimeError('Dataset not found or corrupted.' +
RuntimeError: Dataset not found or corrupted. You can use download=True to download it.

I strictly followed the instruction of Dataset Preparation to construct the dataset of VOC.

Was there something wrong for me?

**Comment by JimZAI** [comment]
The value of "voc_root" in voc.py (line 121) becomes '/mnt/hdd4/xxx/OOD-datasets/VOC/VOCdevkit/VOC2007'.

**Comment by d12306** [comment]
@JimZAI , thanks for your question!

Indeed, the dataset should be downloaded from the official website. I have updated the readme!
